import 'package:menu_makanan/model/makanan.dart';
import 'package:menu_makanan/model/minuman.dart';
import 'package:menu_makanan/model/produk.dart';

class DummyData {
  static List<Produk> getProdukList() {
    return [
      Makanan(
        id: '1',
        nama: 'Rendang',
        deskripsi: 'Masakan daging sapi yang dimasak dengan santan dan rempah khas Padang, kaya rasa dan sangat lezat.',
        harga: 50000,
        gambar: 'assets/rendang.jpeg',
        rating: 1,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '2',
        nama: 'Nasi Goreng',
        deskripsi: 'Nasi yang digoreng dengan bumbu tradisional Indonesia. Disajikan dengan telur mata sapi, ayam, dan kerupuk.',
        harga: 12000,
        gambar: 'assets/nasi goreng.jpg',
        rating: 4.7,
        linkWeb: 'https://www.youtube.com/',
        pedas: false & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '3',
        nama: 'Sate Ayam',
        deskripsi: 'Daging Ayam yang ditusuk dan dibakar, disajikan dengan bumbu kacang khas.',
        harga: 15000,
        gambar: 'assets/sate ayam.jpg',
        rating: 4.6,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '4',
        nama: 'Gado-gado',
        deskripsi: 'Salad sayur dengan bumbu kacang yang kental dan manis, disajikan dengan lontong dan telur rebus.',
        harga: 20000,
        gambar: 'assets/gado gado.jpg',
        rating: 4.6,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '5',
        nama: 'Bakso',
        deskripsi: 'Bola daging sapi yang disajikan dalam kuah kaldu.',
        harga: 15000,
        gambar: 'assets/bakso.jpeg',
        rating: 4.6,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Minuman(
        id: '6',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/es teh manis.jpeg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '7',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/jus alpukat.jpg',
        rating: 4.9,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '8',
        nama: 'Es Jeruk',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/es jeruk.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '9',
        nama: 'Cendol',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/es cendol nangka.jpg',
        rating: 4.9,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '10',
        nama: 'Es Teller',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/es teller.jpg',
        rating: 4.5,
        
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Makanan(
        id: '11',
        nama: 'Classic Rib-Eye Steak',
        deskripsi: 'Daging sapi bagian rib-eye premium Australia, dipanggang sesuai tingkat kematangan pilihan Anda. Disajikan dengan pilihan saus (jamur/lada hitam), kentang goreng, dan mixed salad.',
        harga: 30000,
        gambar: 'assets/Classic Rib-Eye Steak.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '12',
        nama: 'Panna Cotta Mangga',
        deskripsi: 'Puding krim susu khas Italia yang lembut dan ringan, disiram dengan puree mangga harum manis segar di atasnya.',
        harga: 25000,
        gambar: 'assets/pann cotta.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Ringan',
      ),
      Minuman(
        id: '13',
        nama: 'Matcha Latte',
        deskripsi: 'Bubuk matcha murni berkualitas tinggi dari Jepang, dikocok dengan susu segar untuk menciptakan rasa yang creamy dan sedikit pahit (tersedia pilihan panas/dingin).',
        harga: 15000,
        gambar: 'assets/Matcha Latte.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '14',
        nama: 'Sunrise Paradise',
        deskripsi: 'Perpaduan jus jeruk segar, sirup delima (grenadine), dan air soda yang memberikan gradasi warna indah seperti matahari terbit.',
        harga: 12000,
        gambar: 'assets/Sunrise Paradise.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Makanan(
        id: '15',
        nama: 'Crispy Calamari',
        deskripsi: 'Cumi-cumi yang diiris, dibalut tepung berbumbu ringan, lalu digoreng hingga keemasan. Disajikan dengan saus tartar lemon aioli yang menyegarkan.',
        harga: 15000,
        gambar: 'assets/Crispy Calamari.jpg',
        rating: 8,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '11',
        nama: 'Classic Rib-Eye Steak',
        deskripsi: 'Daging sapi bagian rib-eye premium Australia, dipanggang sesuai tingkat kematangan pilihan Anda. Disajikan dengan pilihan saus (jamur/lada hitam), kentang goreng, dan mixed salad.',
        harga: 30000,
        gambar: 'assets/Classic Rib-Eye Steak.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '12',
        nama: 'Panna Cotta Mangga',
        deskripsi: 'Puding krim susu khas Italia yang lembut dan ringan, disiram dengan puree mangga harum manis segar di atasnya.',
        harga: 25000,
        gambar: 'assets/pann cotta.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Ringan',
      ),
      Minuman(
        id: '13',
        nama: 'Matcha Latte',
        deskripsi: 'Bubuk matcha murni berkualitas tinggi dari Jepang, dikocok dengan susu segar untuk menciptakan rasa yang creamy dan sedikit pahit (tersedia pilihan panas/dingin).',
        harga: 15000,
        gambar: 'assets/Matcha Latte.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '14',
        nama: 'Sunrise Paradise',
        deskripsi: 'Perpaduan jus jeruk segar, sirup delima (grenadine), dan air soda yang memberikan gradasi warna indah seperti matahari terbit.',
        harga: 12000,
        gambar: 'assets/Sunrise Paradise.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Makanan(
        id: '15',
        nama: 'Crispy Calamari',
        deskripsi: 'Cumi-cumi yang diiris, dibalut tepung berbumbu ringan, lalu digoreng hingga keemasan. Disajikan dengan saus tartar lemon aioli yang menyegarkan.',
        harga: 15000,
        gambar: 'assets/Crispy Calamari.jpg',
        rating: 8,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
    ];
  }
}
