import 'package:menu_makanan/model/makanan.dart';
import 'package:menu_makanan/model/minuman.dart';
import 'package:menu_makanan/model/produk.dart';

class DummyData {
  static List<Produk> getProdukList() {
    return [
      Makanan(
        id: '1',
        nama: 'Rendang',
        deskripsi: 'Masakan daging sapi yang dimasak dengan santan dan rempah khas Padang, kaya rasa dan sangat lezat.',
        harga: 50000,
        gambar: 'assets/rendang.jpeg',
        rating: 1,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '2',
        nama: 'Nasi Goreng',
        deskripsi: 'Nasi yang digoreng dengan bumbu tradisional Indonesia. Disajikan dengan telur mata sapi, ayam, dan kerupuk.',
        harga: 12000,
        gambar: 'assets/nasi goreng.jpg',
        rating: 4.7,
        linkWeb: 'https://www.youtube.com/',
        pedas: false & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '3',
        nama: 'Sate Ayam',
        deskripsi: 'Daging Ayam yang ditusuk dan dibakar, disajikan dengan bumbu kacang khas.',
        harga: 15000,
        gambar: 'assets/sate ayam.jpg',
        rating: 4.6,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '4',
        nama: 'Gado-gado',
        deskripsi: 'Salad sayur dengan bumbu kacang yang kental dan manis, disajikan dengan lontong dan telur rebus.',
        harga: 20000,
        gambar: 'assets/gado gado.jpg',
        rating: 4.6,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Makanan(
        id: '5',
        nama: 'Bakso',
        deskripsi: 'Bola daging sapi yang disajikan dalam kuah kaldu.',
        harga: 15000,
        gambar: 'assets/bakso.jpeg',
        rating: 4.6,
        linkWeb: 'https://www.youtube.com/',
        pedas: true & false,
        kategori: 'Makanan Berat',
      ),
      Minuman(
        id: '6',
        nama: 'Es Teh Manis',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/es teh manis.jpeg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '7',
        nama: 'Jus Alpukat',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/jus alpukat.jpg',
        rating: 4.9,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '8',
        nama: 'Es Jeruk',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/es jeruk.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
      Minuman(
        id: '9',
        nama: 'Cendol',
        deskripsi: 'Jus alpukat segar dengan susu kental manis dan es serut, memberikan sensasi creamy yang nikmat.',
        harga: 12000,
        gambar: 'assets/es cendol nangka.jpg',
        rating: 4.9,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Besar',
      ),
      Minuman(
        id: '10',
        nama: 'Es Teller',
        deskripsi: 'Es teh manis segar dengan perasan lemon, cocok untuk menemani makanan pedas.',
        harga: 8000,
        gambar: 'assets/es teller.jpg',
        rating: 4.5,
        linkWeb: 'https://www.youtube.com/',
        dingin: true & false,
        ukuran: 'Sedang',
      ),
    ];
  }
}
